### ISSUE TITLE
goods-full questions not listed in Galaxy-Zoo translations

### ISSUE THREAD

**Issue by murraycu** [zooniverse/Translator#11]
This decision tree was added recently and is being used in the web UI:
https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/lib/goods_full_tree.coffee

These new goods-full-* questions (and answers) are not being offered in the translation UI:
http://translations.zooniverse.org/#/projects/galaxy_zoo

And they are not present in the resulting .json file with the translations. For instance:
http://www.galaxyzoo.org/locales/fr.json

**Comment by willettk** [comment]
Right. So the GOODS full-depth images are expected to be finished in a matter of weeks; from a practical viewpoint, it may not merit the effort to put in full translations (especially for the languages that aren't commonly used). On the other hand, we should make sure that the new decision trees do appear in the translation UI so that volunteers have the opportunity to correct these. 

@chrissnyder - what's the mechanism by which new decision trees (or text of any kind on GZ) are added to the translation UI?

**Comment by chrissnyder** [comment]
Should be added now (after a real long delay).
